### ISSUE TITLE
KeyError: 'bounds'

### ISSUE THREAD

**Issue by blairg23** [prodicus/pyzipcode-cli#17]
Quite a few zipcodes, including 95055 (in the US) return an error `KeyError: 'bounds'`.

**Comment by tasdikrahman** [comment]
Hey @blairg23 . Thanks for using  `pyzipcode-cli`. 
Could you paste the exact thing that you tried and the traceback message along with the pyzipcode and python version you are using. Also you OS. Thanks

**Comment by blairg23** [comment]
>>> from pyzipcode import Pyzipcode
    >>> Pyzipcode.get('95055', 'US')
    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "C:\Users\blairg23\AppData\Local\Programs\Python\Python35\lib\site-packages\pyzipcode\pyzipcode.py", line 85, in get data_API_2 = Pyzipcode.query_google_api(pincode)
    File "C:\Users\blairg23\AppData\Local\Programs\Python\Python35\lib\site-packages\pyzipcode\pyzipcode.py", line 61, in query_google_api "bounds": results["bounds"]
    KeyError: 'bounds'

On both Ubuntu LTS and Windows 10, Python3.

**Comment by blairg23** [comment]
Found another:

    >>> Pyzipcode.get('95617', 'US')
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/blairg/.virtualenvs/tomis-data/lib/python3.5/site-packages/pyzipcode/pyzipcode.py", line 85, in get
        data_API_2 = Pyzipcode.query_google_api(pincode)
      File "/home/blairg/.virtualenvs/tomis-data/lib/python3.5/site-packages/pyzipcode/pyzipcode.py", line 61, in query_google_api
    "bounds": results["bounds"]
    KeyError: 'bounds'

**Comment by blairg23** [comment]
I think the fix is you need to try/except around the Google API call and only insert what values the request returns, instead of assuming `bounds` will always exist.

**Comment by WuZhuoran** [comment]
Same issue.
How to fix it?

**Comment by blairg23** [comment]
Just use a better library like geocoder: http://geocoder.readthedocs.io

Much more robust and doesn't force you into a wrapper without any error
handling.
